name: Build Flutter APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      # 📌 working-directory එක ලෙස ඔයාගේ folder name එක දෙන්න
      - name: Install Dependencies
        run: flutter pub get
        working-directory: ./mygame  # <-- ඔයාගේ folder name එක මෙතනට දාන්න

      - name: Build Android Release APK
        run: flutter build apk --release --no-tree-shake-icons
        working-directory: ./mygame  # <-- ඔයාගේ folder name එක මෙතනට දාන්න

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MYGame-App-Release
          path: mygame/build/app/outputs/flutter-apk/app-release.apk
